### TauAge (Hipp) model to predict age adjusted hippocampal pTau in PWG (1D,S2C)

```{r}
library(tidyverse)
library(SummarizedExperiment)
library(glmnet)
library(dnaMethyAge)
source("~/hepler_functions.R")

#Compute age adjusted pTau residual
se <- readRDS("~/PART_AD/PWG/PWG_SE.rds")
smry <- readRDS("~/PART_AD/PWG/PWG_PART_pTau_EWAS.rds") #EWAS - run previously
meta <- colData(se) %>% as.data.frame()
meta$log_pTau <- log(meta$hippocampus_proper_aperio_quants + 1)
pTau_age_model <- lm(log_pTau ~ age,data=meta) #linear model to predict pTau based on age
meta$log_pTau_age_adjusted <- meta$log_pTau - predict(pTau_age_model,meta) #actual - predicted pTau based on age

#divide training and testing data
mtx <- cleanMatrixForClusterW(assay(se)) %>% imputeRowMean(.) 
m <- meta %>% filter(sex == "M") %>% pull(meth_id)
set.seed(123)
f <- meta %>% filter(sex == "F") %>% pull(meth_id) %>% sample(.,length(m))
train_m <- sample(m,ceiling(length(m) * .8))
train_f <- sample(f,ceiling(length(f) * .8))
test_m <- m[!m %in% train_m]
test_f <- c(f[!f %in% train_f],meta$meth_id[!meta$meth_id %in% c(m,f)]) #get remaining female testing samples 

#Train models
trainEN <- function(betas,pTau,...) {
  fit <- cv.glmnet(
    betas,
    pTau,
    nfolds=10,
    alpha=0.5,
    type.measure="mse",
    family="gaussian",
    ...
  )
  fit
}

feat <- smry %>% arrange(FDR_log_pTau) %>% pull(Probe_ID)
feat <- feat[feat %in% rownames(mtx)]
feat <- feat[!grepl("rs|ctl",feat)]
n_feat <- seq(2000,30000,2000)

train_mtx <- mtx[,c(train_m,train_f)]
train_pTau_age_adjusted <- meta[c(train_m,train_f),"log_pTau_age_adjusted"]

tau_age_models <- mclapply(n_feat,function(x) {
  cgs <- feat[1:x]
  na_rm <- which(is.na(train_pTau_age_adjusted))
  train_pTau_age_adjusted <- train_pTau_age_adjusted[-na_rm]
  mtx2 <- t(train_mtx[cgs,-na_rm])
  model <- trainEN(betas=mtx2,pTau = train_pTau_age_adjusted)
},mc.cores=40) 
names(tau_age_models) <- paste0("Model_",as.character(n_feat))


#predict on testing data
test_mtx <-  t(mtx[,c(test_m,test_f)])
test_pTau_age_adjusted <- meta[rownames(test_mtx),"log_pTau_age_adjusted"]

testEN <- function(model,betas) {
  cgs <- rownames(coef(model))[-1]
  betas <- betas[,cgs]
  predict(model,se=model[["lambda.min"]],newx=betas,type="response")
}

tau_age_models_stat <- do.call(rbind,lapply(seq(tau_age_models),function(x) {
  model <- tau_age_models[[x]]
  predicted <- testEN(model=model,betas=test_mtx)
  res <- cor.test(test_pTau_age_adjusted,predicted)
  data.frame(
    Model=as.character(x),
    Cor=res$estimate,
    P=res$p.value
  )
}))
  
max_cor <- max(tau_age_models_stat$Cor)
tau_age_hipp <- tau_age_models[[which(tau_age_models_stat$Cor == max_cor)]]

#predict again on all samples for summary stats
pred <- testEN(model=tau_age_hipp,betas=t(mtx))

tau_age_hipp_smry <- data.frame(
  Sample=meta$meth_id,
  Sex=meta$sex,
  Predicted=pred[,1],
  Actual=meta$log_pTau_age_adjusted
)
```

### Test whether model cgs associate with regular and epigenetic aging (S2C,D)
```{r}
se <- readRDS("~/PART_AD/PWG/PWG_SE.rds")
se2 <- cleanMatrixForClusterSE(se,f_row = .75) #75% coverage across samples

getModelCGs <- function(model) {
  tmp_coeffs <- coef(model, s = "lambda.min")
  cgs <- tmp_coeffs@Dimnames[[1]][tmp_coeffs@i + 1][-1]
  return(cgs)
}

tau_age_hipp_cgs <- getModelCGs(tau_age_hipp)

res <- DML(se2,~age + sex + sample_plate,BPPARAM=BiocParallel::MulticoreParam(40))
smry <- summaryExtractTest(res)
smry <- smry %>%
  mutate(FDR_age=p.adjust(Pval_age,method="fdr")) %>%
  mutate(TauAge_CpG=
           case_when(
             Probe_ID %in% tau_age_hipp_cgs ~ "Y",
             TRUE ~ "N"
             ))

#Compute epigenetic age prediction and compare with tau age
library(dnaMethyAge)
betas <- assay(se) %>% imputeRowMean(.)

age_info <- data.frame(
  Sample=colnames(betas),
  Age=colData(se)$age
)

epi_age_Horvath <- methyAge(
  betas, 
  clock="HorvathS2013",
  simple_mode=FALSE,
  age_info=age_info,
  fit_method='Linear',
  do_plot=FALSE
) 

epi_age_Horvath$log_pTau <- meta[epi_age_Horvath$Sample,"log_pTau"]
epi_age_Horvath$log_pTau_age_adjusted <- meta[epi_age_Horvath$Sample,"log_pTau_age_adjusted"]
cor.test(epi_age_Horvath$Age_Acceleration,epi_age_Horvath$log_pTau) 
cor.test(epi_age_Horvath$Age_Acceleration,epi_age_Horvath$log_pTau_age_adjusted) 

cortical_coef <- read_delim("~/CorticalClock/CorticalClock/PredCorticalAge/CorticalClockCoefs.txt",delim=" ")
load("~/CorticalClock/CorticalClock/PredCorticalAge/Ref_DNAm_brain_values.rdat") #Download from Shireby 2020 PMID:33300551

missing <- apply(betas[cortical_coef$probe,],1,function(x) sum(is.na(x)) == ncol(betas))
missing <- names(which(missing))
for (cg in missing) {
  beta <- unname(ref[cg])
  betas[cg,] <- beta
}

epi_age_Cortical <- methyAge(
  betas, 
  clock="ShirebyG2020",
  simple_mode=FALSE,
  age_info=age_info,
  fit_method='Linear',
  do_plot=FALSE
) 

epi_age_Cortical$log_pTau <- meta[epi_age_Cortical$Sample,"log_pTau"]
epi_age_Cortical$log_pTau_age_adjusted <- meta[epi_age_Cortical$Sample,"log_pTau_age_adjusted"]
cor.test(epi_age_Cortical$Age_Acceleration,epi_age_Cortical$log_pTau) 
cor.test(epi_age_Cortical$Age_Acceleration,epi_age_Cortical$log_pTau_age_adjusted) 
```
